/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TossRouteImport } from './routes/toss'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InformasiKehamilanRouteImport } from './routes/informasi-kehamilan'
import { Route as IbuHamilTanpaTbRouteImport } from './routes/ibu-hamil-tanpa-tb'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DeteksiDiniTbRouteImport } from './routes/deteksi-dini-tb'
import { Route as CekRisikoRouteImport } from './routes/cek-risiko'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PemeriksaanResikoIndexRouteImport } from './routes/pemeriksaan-resiko/index'
import { Route as PemeriksaanMandiriIndexRouteImport } from './routes/pemeriksaan-mandiri/index'
import { Route as EducationIndexRouteImport } from './routes/education/index'
import { Route as PemeriksaanResikoHasilRouteImport } from './routes/pemeriksaan-resiko/hasil'
import { Route as PemeriksaanMandiriHasilRouteImport } from './routes/pemeriksaan-mandiri/hasil'
import { Route as InformasiKehamilanTandaBahayaRouteImport } from './routes/informasi-kehamilan/tanda-bahaya'
import { Route as InformasiKehamilanPengelolaanRouteImport } from './routes/informasi-kehamilan/pengelolaan'
import { Route as InformasiKehamilanMasalahRouteImport } from './routes/informasi-kehamilan/masalah'
import { Route as InformasiKehamilanLaranganRouteImport } from './routes/informasi-kehamilan/larangan'
import { Route as EducationVideoRouteImport } from './routes/education/video'
import { Route as EducationFlipbookRouteImport } from './routes/education/flipbook'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as EducationFlipbookIndexRouteImport } from './routes/education/flipbook/index'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as EducationFlipbookIdRouteImport } from './routes/education/flipbook/$id'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const TossRoute = TossRouteImport.update({
  id: '/toss',
  path: '/toss',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiKehamilanRoute = InformasiKehamilanRouteImport.update({
  id: '/informasi-kehamilan',
  path: '/informasi-kehamilan',
  getParentRoute: () => rootRouteImport,
} as any)
const IbuHamilTanpaTbRoute = IbuHamilTanpaTbRouteImport.update({
  id: '/ibu-hamil-tanpa-tb',
  path: '/ibu-hamil-tanpa-tb',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DeteksiDiniTbRoute = DeteksiDiniTbRouteImport.update({
  id: '/deteksi-dini-tb',
  path: '/deteksi-dini-tb',
  getParentRoute: () => rootRouteImport,
} as any)
const CekRisikoRoute = CekRisikoRouteImport.update({
  id: '/cek-risiko',
  path: '/cek-risiko',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanResikoIndexRoute = PemeriksaanResikoIndexRouteImport.update({
  id: '/pemeriksaan-resiko/',
  path: '/pemeriksaan-resiko/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriIndexRoute = PemeriksaanMandiriIndexRouteImport.update({
  id: '/pemeriksaan-mandiri/',
  path: '/pemeriksaan-mandiri/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationRoute,
} as any)
const PemeriksaanResikoHasilRoute = PemeriksaanResikoHasilRouteImport.update({
  id: '/pemeriksaan-resiko/hasil',
  path: '/pemeriksaan-resiko/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriHasilRoute = PemeriksaanMandiriHasilRouteImport.update({
  id: '/pemeriksaan-mandiri/hasil',
  path: '/pemeriksaan-mandiri/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiKehamilanTandaBahayaRoute =
  InformasiKehamilanTandaBahayaRouteImport.update({
    id: '/tanda-bahaya',
    path: '/tanda-bahaya',
    getParentRoute: () => InformasiKehamilanRoute,
  } as any)
const InformasiKehamilanPengelolaanRoute =
  InformasiKehamilanPengelolaanRouteImport.update({
    id: '/pengelolaan',
    path: '/pengelolaan',
    getParentRoute: () => InformasiKehamilanRoute,
  } as any)
const InformasiKehamilanMasalahRoute =
  InformasiKehamilanMasalahRouteImport.update({
    id: '/masalah',
    path: '/masalah',
    getParentRoute: () => InformasiKehamilanRoute,
  } as any)
const InformasiKehamilanLaranganRoute =
  InformasiKehamilanLaranganRouteImport.update({
    id: '/larangan',
    path: '/larangan',
    getParentRoute: () => InformasiKehamilanRoute,
  } as any)
const EducationVideoRoute = EducationVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => EducationRoute,
} as any)
const EducationFlipbookRoute = EducationFlipbookRouteImport.update({
  id: '/flipbook',
  path: '/flipbook',
  getParentRoute: () => EducationRoute,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const EducationFlipbookIndexRoute = EducationFlipbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationFlipbookRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const EducationFlipbookIdRoute = EducationFlipbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EducationFlipbookRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cek-risiko': typeof CekRisikoRoute
  '/deteksi-dini-tb': typeof DeteksiDiniTbRoute
  '/education': typeof EducationRouteWithChildren
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/informasi-kehamilan': typeof InformasiKehamilanRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/education/flipbook': typeof EducationFlipbookRouteWithChildren
  '/education/video': typeof EducationVideoRoute
  '/informasi-kehamilan/larangan': typeof InformasiKehamilanLaranganRoute
  '/informasi-kehamilan/masalah': typeof InformasiKehamilanMasalahRoute
  '/informasi-kehamilan/pengelolaan': typeof InformasiKehamilanPengelolaanRoute
  '/informasi-kehamilan/tanda-bahaya': typeof InformasiKehamilanTandaBahayaRoute
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/education/': typeof EducationIndexRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/education/flipbook/': typeof EducationFlipbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cek-risiko': typeof CekRisikoRoute
  '/deteksi-dini-tb': typeof DeteksiDiniTbRoute
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/informasi-kehamilan': typeof InformasiKehamilanRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/education/video': typeof EducationVideoRoute
  '/informasi-kehamilan/larangan': typeof InformasiKehamilanLaranganRoute
  '/informasi-kehamilan/masalah': typeof InformasiKehamilanMasalahRoute
  '/informasi-kehamilan/pengelolaan': typeof InformasiKehamilanPengelolaanRoute
  '/informasi-kehamilan/tanda-bahaya': typeof InformasiKehamilanTandaBahayaRoute
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/education': typeof EducationIndexRoute
  '/pemeriksaan-mandiri': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/education/flipbook': typeof EducationFlipbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/cek-risiko': typeof CekRisikoRoute
  '/deteksi-dini-tb': typeof DeteksiDiniTbRoute
  '/education': typeof EducationRouteWithChildren
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/informasi-kehamilan': typeof InformasiKehamilanRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/education/flipbook': typeof EducationFlipbookRouteWithChildren
  '/education/video': typeof EducationVideoRoute
  '/informasi-kehamilan/larangan': typeof InformasiKehamilanLaranganRoute
  '/informasi-kehamilan/masalah': typeof InformasiKehamilanMasalahRoute
  '/informasi-kehamilan/pengelolaan': typeof InformasiKehamilanPengelolaanRoute
  '/informasi-kehamilan/tanda-bahaya': typeof InformasiKehamilanTandaBahayaRoute
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/education/': typeof EducationIndexRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/education/flipbook/': typeof EducationFlipbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cek-risiko'
    | '/deteksi-dini-tb'
    | '/education'
    | '/ibu-hamil-tanpa-tb'
    | '/informasi-kehamilan'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/posts'
    | '/education/flipbook'
    | '/education/video'
    | '/informasi-kehamilan/larangan'
    | '/informasi-kehamilan/masalah'
    | '/informasi-kehamilan/pengelolaan'
    | '/informasi-kehamilan/tanda-bahaya'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/education/'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/posts/$postId'
    | '/education/flipbook/$id'
    | '/posts/'
    | '/education/flipbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cek-risiko'
    | '/deteksi-dini-tb'
    | '/ibu-hamil-tanpa-tb'
    | '/informasi-kehamilan'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/education/video'
    | '/informasi-kehamilan/larangan'
    | '/informasi-kehamilan/masalah'
    | '/informasi-kehamilan/pengelolaan'
    | '/informasi-kehamilan/tanda-bahaya'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/education'
    | '/pemeriksaan-mandiri'
    | '/pemeriksaan-resiko'
    | '/posts/$postId'
    | '/education/flipbook/$id'
    | '/posts'
    | '/education/flipbook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/cek-risiko'
    | '/deteksi-dini-tb'
    | '/education'
    | '/ibu-hamil-tanpa-tb'
    | '/informasi-kehamilan'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/_authed/posts'
    | '/education/flipbook'
    | '/education/video'
    | '/informasi-kehamilan/larangan'
    | '/informasi-kehamilan/masalah'
    | '/informasi-kehamilan/pengelolaan'
    | '/informasi-kehamilan/tanda-bahaya'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/education/'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/_authed/posts/$postId'
    | '/education/flipbook/$id'
    | '/_authed/posts/'
    | '/education/flipbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CekRisikoRoute: typeof CekRisikoRoute
  DeteksiDiniTbRoute: typeof DeteksiDiniTbRoute
  EducationRoute: typeof EducationRouteWithChildren
  IbuHamilTanpaTbRoute: typeof IbuHamilTanpaTbRoute
  InformasiKehamilanRoute: typeof InformasiKehamilanRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  QuizRoute: typeof QuizRoute
  SignupRoute: typeof SignupRoute
  TossRoute: typeof TossRoute
  PemeriksaanMandiriHasilRoute: typeof PemeriksaanMandiriHasilRoute
  PemeriksaanResikoHasilRoute: typeof PemeriksaanResikoHasilRoute
  PemeriksaanMandiriIndexRoute: typeof PemeriksaanMandiriIndexRoute
  PemeriksaanResikoIndexRoute: typeof PemeriksaanResikoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toss': {
      id: '/toss'
      path: '/toss'
      fullPath: '/toss'
      preLoaderRoute: typeof TossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan': {
      id: '/informasi-kehamilan'
      path: '/informasi-kehamilan'
      fullPath: '/informasi-kehamilan'
      preLoaderRoute: typeof InformasiKehamilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ibu-hamil-tanpa-tb': {
      id: '/ibu-hamil-tanpa-tb'
      path: '/ibu-hamil-tanpa-tb'
      fullPath: '/ibu-hamil-tanpa-tb'
      preLoaderRoute: typeof IbuHamilTanpaTbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deteksi-dini-tb': {
      id: '/deteksi-dini-tb'
      path: '/deteksi-dini-tb'
      fullPath: '/deteksi-dini-tb'
      preLoaderRoute: typeof DeteksiDiniTbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-risiko': {
      id: '/cek-risiko'
      path: '/cek-risiko'
      fullPath: '/cek-risiko'
      preLoaderRoute: typeof CekRisikoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-resiko/': {
      id: '/pemeriksaan-resiko/'
      path: '/pemeriksaan-resiko'
      fullPath: '/pemeriksaan-resiko/'
      preLoaderRoute: typeof PemeriksaanResikoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/': {
      id: '/pemeriksaan-mandiri/'
      path: '/pemeriksaan-mandiri'
      fullPath: '/pemeriksaan-mandiri/'
      preLoaderRoute: typeof PemeriksaanMandiriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/': {
      id: '/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof EducationRoute
    }
    '/pemeriksaan-resiko/hasil': {
      id: '/pemeriksaan-resiko/hasil'
      path: '/pemeriksaan-resiko/hasil'
      fullPath: '/pemeriksaan-resiko/hasil'
      preLoaderRoute: typeof PemeriksaanResikoHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/hasil': {
      id: '/pemeriksaan-mandiri/hasil'
      path: '/pemeriksaan-mandiri/hasil'
      fullPath: '/pemeriksaan-mandiri/hasil'
      preLoaderRoute: typeof PemeriksaanMandiriHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/tanda-bahaya': {
      id: '/informasi-kehamilan/tanda-bahaya'
      path: '/tanda-bahaya'
      fullPath: '/informasi-kehamilan/tanda-bahaya'
      preLoaderRoute: typeof InformasiKehamilanTandaBahayaRouteImport
      parentRoute: typeof InformasiKehamilanRoute
    }
    '/informasi-kehamilan/pengelolaan': {
      id: '/informasi-kehamilan/pengelolaan'
      path: '/pengelolaan'
      fullPath: '/informasi-kehamilan/pengelolaan'
      preLoaderRoute: typeof InformasiKehamilanPengelolaanRouteImport
      parentRoute: typeof InformasiKehamilanRoute
    }
    '/informasi-kehamilan/masalah': {
      id: '/informasi-kehamilan/masalah'
      path: '/masalah'
      fullPath: '/informasi-kehamilan/masalah'
      preLoaderRoute: typeof InformasiKehamilanMasalahRouteImport
      parentRoute: typeof InformasiKehamilanRoute
    }
    '/informasi-kehamilan/larangan': {
      id: '/informasi-kehamilan/larangan'
      path: '/larangan'
      fullPath: '/informasi-kehamilan/larangan'
      preLoaderRoute: typeof InformasiKehamilanLaranganRouteImport
      parentRoute: typeof InformasiKehamilanRoute
    }
    '/education/video': {
      id: '/education/video'
      path: '/video'
      fullPath: '/education/video'
      preLoaderRoute: typeof EducationVideoRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/flipbook': {
      id: '/education/flipbook'
      path: '/flipbook'
      fullPath: '/education/flipbook'
      preLoaderRoute: typeof EducationFlipbookRouteImport
      parentRoute: typeof EducationRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/education/flipbook/': {
      id: '/education/flipbook/'
      path: '/'
      fullPath: '/education/flipbook/'
      preLoaderRoute: typeof EducationFlipbookIndexRouteImport
      parentRoute: typeof EducationFlipbookRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/education/flipbook/$id': {
      id: '/education/flipbook/$id'
      path: '/$id'
      fullPath: '/education/flipbook/$id'
      preLoaderRoute: typeof EducationFlipbookIdRouteImport
      parentRoute: typeof EducationFlipbookRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
  }
}

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface EducationFlipbookRouteChildren {
  EducationFlipbookIdRoute: typeof EducationFlipbookIdRoute
  EducationFlipbookIndexRoute: typeof EducationFlipbookIndexRoute
}

const EducationFlipbookRouteChildren: EducationFlipbookRouteChildren = {
  EducationFlipbookIdRoute: EducationFlipbookIdRoute,
  EducationFlipbookIndexRoute: EducationFlipbookIndexRoute,
}

const EducationFlipbookRouteWithChildren =
  EducationFlipbookRoute._addFileChildren(EducationFlipbookRouteChildren)

interface EducationRouteChildren {
  EducationFlipbookRoute: typeof EducationFlipbookRouteWithChildren
  EducationVideoRoute: typeof EducationVideoRoute
  EducationIndexRoute: typeof EducationIndexRoute
}

const EducationRouteChildren: EducationRouteChildren = {
  EducationFlipbookRoute: EducationFlipbookRouteWithChildren,
  EducationVideoRoute: EducationVideoRoute,
  EducationIndexRoute: EducationIndexRoute,
}

const EducationRouteWithChildren = EducationRoute._addFileChildren(
  EducationRouteChildren,
)

interface InformasiKehamilanRouteChildren {
  InformasiKehamilanLaranganRoute: typeof InformasiKehamilanLaranganRoute
  InformasiKehamilanMasalahRoute: typeof InformasiKehamilanMasalahRoute
  InformasiKehamilanPengelolaanRoute: typeof InformasiKehamilanPengelolaanRoute
  InformasiKehamilanTandaBahayaRoute: typeof InformasiKehamilanTandaBahayaRoute
}

const InformasiKehamilanRouteChildren: InformasiKehamilanRouteChildren = {
  InformasiKehamilanLaranganRoute: InformasiKehamilanLaranganRoute,
  InformasiKehamilanMasalahRoute: InformasiKehamilanMasalahRoute,
  InformasiKehamilanPengelolaanRoute: InformasiKehamilanPengelolaanRoute,
  InformasiKehamilanTandaBahayaRoute: InformasiKehamilanTandaBahayaRoute,
}

const InformasiKehamilanRouteWithChildren =
  InformasiKehamilanRoute._addFileChildren(InformasiKehamilanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CekRisikoRoute: CekRisikoRoute,
  DeteksiDiniTbRoute: DeteksiDiniTbRoute,
  EducationRoute: EducationRouteWithChildren,
  IbuHamilTanpaTbRoute: IbuHamilTanpaTbRoute,
  InformasiKehamilanRoute: InformasiKehamilanRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  QuizRoute: QuizRoute,
  SignupRoute: SignupRoute,
  TossRoute: TossRoute,
  PemeriksaanMandiriHasilRoute: PemeriksaanMandiriHasilRoute,
  PemeriksaanResikoHasilRoute: PemeriksaanResikoHasilRoute,
  PemeriksaanMandiriIndexRoute: PemeriksaanMandiriIndexRoute,
  PemeriksaanResikoIndexRoute: PemeriksaanResikoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
