/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PemeriksaanResikoIndexRouteImport } from './routes/pemeriksaan-resiko/index'
import { Route as PemeriksaanMandiriIndexRouteImport } from './routes/pemeriksaan-mandiri/index'
import { Route as PemeriksaanResikoHasilRouteImport } from './routes/pemeriksaan-resiko/hasil'
import { Route as PemeriksaanMandiriHasilRouteImport } from './routes/pemeriksaan-mandiri/hasil'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanResikoIndexRoute = PemeriksaanResikoIndexRouteImport.update({
  id: '/pemeriksaan-resiko/',
  path: '/pemeriksaan-resiko/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriIndexRoute = PemeriksaanMandiriIndexRouteImport.update({
  id: '/pemeriksaan-mandiri/',
  path: '/pemeriksaan-mandiri/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanResikoHasilRoute = PemeriksaanResikoHasilRouteImport.update({
  id: '/pemeriksaan-resiko/hasil',
  path: '/pemeriksaan-resiko/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriHasilRoute = PemeriksaanMandiriHasilRouteImport.update({
  id: '/pemeriksaan-mandiri/hasil',
  path: '/pemeriksaan-mandiri/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/pemeriksaan-mandiri': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/posts'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/posts/$postId'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/pemeriksaan-mandiri'
    | '/pemeriksaan-resiko'
    | '/posts/$postId'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/posts'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/_authed/posts/$postId'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  PemeriksaanMandiriHasilRoute: typeof PemeriksaanMandiriHasilRoute
  PemeriksaanResikoHasilRoute: typeof PemeriksaanResikoHasilRoute
  PemeriksaanMandiriIndexRoute: typeof PemeriksaanMandiriIndexRoute
  PemeriksaanResikoIndexRoute: typeof PemeriksaanResikoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-resiko/': {
      id: '/pemeriksaan-resiko/'
      path: '/pemeriksaan-resiko'
      fullPath: '/pemeriksaan-resiko/'
      preLoaderRoute: typeof PemeriksaanResikoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/': {
      id: '/pemeriksaan-mandiri/'
      path: '/pemeriksaan-mandiri'
      fullPath: '/pemeriksaan-mandiri/'
      preLoaderRoute: typeof PemeriksaanMandiriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-resiko/hasil': {
      id: '/pemeriksaan-resiko/hasil'
      path: '/pemeriksaan-resiko/hasil'
      fullPath: '/pemeriksaan-resiko/hasil'
      preLoaderRoute: typeof PemeriksaanResikoHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/hasil': {
      id: '/pemeriksaan-mandiri/hasil'
      path: '/pemeriksaan-mandiri/hasil'
      fullPath: '/pemeriksaan-mandiri/hasil'
      preLoaderRoute: typeof PemeriksaanMandiriHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
  }
}

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  PemeriksaanMandiriHasilRoute: PemeriksaanMandiriHasilRoute,
  PemeriksaanResikoHasilRoute: PemeriksaanResikoHasilRoute,
  PemeriksaanMandiriIndexRoute: PemeriksaanMandiriIndexRoute,
  PemeriksaanResikoIndexRoute: PemeriksaanResikoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
