/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TossRouteImport } from './routes/toss'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IbuHamilTanpaTbRouteImport } from './routes/ibu-hamil-tanpa-tb'
import { Route as EducationRouteImport } from './routes/education'
import { Route as CekRisikoRouteImport } from './routes/cek-risiko'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PemeriksaanResikoIndexRouteImport } from './routes/pemeriksaan-resiko/index'
import { Route as PemeriksaanMandiriIndexRouteImport } from './routes/pemeriksaan-mandiri/index'
import { Route as InformasiKehamilanIndexRouteImport } from './routes/informasi-kehamilan/index'
import { Route as EducationIndexRouteImport } from './routes/education/index'
import { Route as DeteksiDiniTbIndexRouteImport } from './routes/deteksi-dini-tb/index'
import { Route as PemeriksaanResikoHasilRouteImport } from './routes/pemeriksaan-resiko/hasil'
import { Route as PemeriksaanMandiriHasilRouteImport } from './routes/pemeriksaan-mandiri/hasil'
import { Route as EducationVideoRouteImport } from './routes/education/video'
import { Route as EducationFlipbookRouteImport } from './routes/education/flipbook'
import { Route as DeteksiDiniTbSkriningRouteImport } from './routes/deteksi-dini-tb/skrining'
import { Route as DeteksiDiniTbHasilRouteImport } from './routes/deteksi-dini-tb/hasil'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as InformasiKehamilanTandaBahayaIndexRouteImport } from './routes/informasi-kehamilan/tanda-bahaya/index'
import { Route as InformasiKehamilanPengelolaanIndexRouteImport } from './routes/informasi-kehamilan/pengelolaan/index'
import { Route as InformasiKehamilanMasalahIndexRouteImport } from './routes/informasi-kehamilan/masalah/index'
import { Route as InformasiKehamilanLaranganIndexRouteImport } from './routes/informasi-kehamilan/larangan/index'
import { Route as EducationVideoIndexRouteImport } from './routes/education/video/index'
import { Route as EducationFlipbookIndexRouteImport } from './routes/education/flipbook/index'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as InformasiKehamilanPengelolaanPengelolaanIdRouteImport } from './routes/informasi-kehamilan/pengelolaan/$pengelolaanId'
import { Route as InformasiKehamilanMasalahMasalahIdRouteImport } from './routes/informasi-kehamilan/masalah/$masalahId'
import { Route as EducationVideoIdRouteImport } from './routes/education/video/$id'
import { Route as EducationFlipbookIdRouteImport } from './routes/education/flipbook/$id'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const TossRoute = TossRouteImport.update({
  id: '/toss',
  path: '/toss',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IbuHamilTanpaTbRoute = IbuHamilTanpaTbRouteImport.update({
  id: '/ibu-hamil-tanpa-tb',
  path: '/ibu-hamil-tanpa-tb',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CekRisikoRoute = CekRisikoRouteImport.update({
  id: '/cek-risiko',
  path: '/cek-risiko',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanResikoIndexRoute = PemeriksaanResikoIndexRouteImport.update({
  id: '/pemeriksaan-resiko/',
  path: '/pemeriksaan-resiko/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriIndexRoute = PemeriksaanMandiriIndexRouteImport.update({
  id: '/pemeriksaan-mandiri/',
  path: '/pemeriksaan-mandiri/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiKehamilanIndexRoute = InformasiKehamilanIndexRouteImport.update({
  id: '/informasi-kehamilan/',
  path: '/informasi-kehamilan/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationRoute,
} as any)
const DeteksiDiniTbIndexRoute = DeteksiDiniTbIndexRouteImport.update({
  id: '/deteksi-dini-tb/',
  path: '/deteksi-dini-tb/',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanResikoHasilRoute = PemeriksaanResikoHasilRouteImport.update({
  id: '/pemeriksaan-resiko/hasil',
  path: '/pemeriksaan-resiko/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanMandiriHasilRoute = PemeriksaanMandiriHasilRouteImport.update({
  id: '/pemeriksaan-mandiri/hasil',
  path: '/pemeriksaan-mandiri/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationVideoRoute = EducationVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => EducationRoute,
} as any)
const EducationFlipbookRoute = EducationFlipbookRouteImport.update({
  id: '/flipbook',
  path: '/flipbook',
  getParentRoute: () => EducationRoute,
} as any)
const DeteksiDiniTbSkriningRoute = DeteksiDiniTbSkriningRouteImport.update({
  id: '/deteksi-dini-tb/skrining',
  path: '/deteksi-dini-tb/skrining',
  getParentRoute: () => rootRouteImport,
} as any)
const DeteksiDiniTbHasilRoute = DeteksiDiniTbHasilRouteImport.update({
  id: '/deteksi-dini-tb/hasil',
  path: '/deteksi-dini-tb/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const InformasiKehamilanTandaBahayaIndexRoute =
  InformasiKehamilanTandaBahayaIndexRouteImport.update({
    id: '/informasi-kehamilan/tanda-bahaya/',
    path: '/informasi-kehamilan/tanda-bahaya/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformasiKehamilanPengelolaanIndexRoute =
  InformasiKehamilanPengelolaanIndexRouteImport.update({
    id: '/informasi-kehamilan/pengelolaan/',
    path: '/informasi-kehamilan/pengelolaan/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformasiKehamilanMasalahIndexRoute =
  InformasiKehamilanMasalahIndexRouteImport.update({
    id: '/informasi-kehamilan/masalah/',
    path: '/informasi-kehamilan/masalah/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformasiKehamilanLaranganIndexRoute =
  InformasiKehamilanLaranganIndexRouteImport.update({
    id: '/informasi-kehamilan/larangan/',
    path: '/informasi-kehamilan/larangan/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EducationVideoIndexRoute = EducationVideoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationVideoRoute,
} as any)
const EducationFlipbookIndexRoute = EducationFlipbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationFlipbookRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const InformasiKehamilanPengelolaanPengelolaanIdRoute =
  InformasiKehamilanPengelolaanPengelolaanIdRouteImport.update({
    id: '/informasi-kehamilan/pengelolaan/$pengelolaanId',
    path: '/informasi-kehamilan/pengelolaan/$pengelolaanId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformasiKehamilanMasalahMasalahIdRoute =
  InformasiKehamilanMasalahMasalahIdRouteImport.update({
    id: '/informasi-kehamilan/masalah/$masalahId',
    path: '/informasi-kehamilan/masalah/$masalahId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EducationVideoIdRoute = EducationVideoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EducationVideoRoute,
} as any)
const EducationFlipbookIdRoute = EducationFlipbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EducationFlipbookRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cek-risiko': typeof CekRisikoRoute
  '/education': typeof EducationRouteWithChildren
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/deteksi-dini-tb/hasil': typeof DeteksiDiniTbHasilRoute
  '/deteksi-dini-tb/skrining': typeof DeteksiDiniTbSkriningRoute
  '/education/flipbook': typeof EducationFlipbookRouteWithChildren
  '/education/video': typeof EducationVideoRouteWithChildren
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/deteksi-dini-tb/': typeof DeteksiDiniTbIndexRoute
  '/education/': typeof EducationIndexRoute
  '/informasi-kehamilan/': typeof InformasiKehamilanIndexRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/education/video/$id': typeof EducationVideoIdRoute
  '/informasi-kehamilan/masalah/$masalahId': typeof InformasiKehamilanMasalahMasalahIdRoute
  '/informasi-kehamilan/pengelolaan/$pengelolaanId': typeof InformasiKehamilanPengelolaanPengelolaanIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/education/flipbook/': typeof EducationFlipbookIndexRoute
  '/education/video/': typeof EducationVideoIndexRoute
  '/informasi-kehamilan/larangan/': typeof InformasiKehamilanLaranganIndexRoute
  '/informasi-kehamilan/masalah/': typeof InformasiKehamilanMasalahIndexRoute
  '/informasi-kehamilan/pengelolaan/': typeof InformasiKehamilanPengelolaanIndexRoute
  '/informasi-kehamilan/tanda-bahaya/': typeof InformasiKehamilanTandaBahayaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cek-risiko': typeof CekRisikoRoute
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/deteksi-dini-tb/hasil': typeof DeteksiDiniTbHasilRoute
  '/deteksi-dini-tb/skrining': typeof DeteksiDiniTbSkriningRoute
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/deteksi-dini-tb': typeof DeteksiDiniTbIndexRoute
  '/education': typeof EducationIndexRoute
  '/informasi-kehamilan': typeof InformasiKehamilanIndexRoute
  '/pemeriksaan-mandiri': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko': typeof PemeriksaanResikoIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/education/video/$id': typeof EducationVideoIdRoute
  '/informasi-kehamilan/masalah/$masalahId': typeof InformasiKehamilanMasalahMasalahIdRoute
  '/informasi-kehamilan/pengelolaan/$pengelolaanId': typeof InformasiKehamilanPengelolaanPengelolaanIdRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/education/flipbook': typeof EducationFlipbookIndexRoute
  '/education/video': typeof EducationVideoIndexRoute
  '/informasi-kehamilan/larangan': typeof InformasiKehamilanLaranganIndexRoute
  '/informasi-kehamilan/masalah': typeof InformasiKehamilanMasalahIndexRoute
  '/informasi-kehamilan/pengelolaan': typeof InformasiKehamilanPengelolaanIndexRoute
  '/informasi-kehamilan/tanda-bahaya': typeof InformasiKehamilanTandaBahayaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/cek-risiko': typeof CekRisikoRoute
  '/education': typeof EducationRouteWithChildren
  '/ibu-hamil-tanpa-tb': typeof IbuHamilTanpaTbRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/toss': typeof TossRoute
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/deteksi-dini-tb/hasil': typeof DeteksiDiniTbHasilRoute
  '/deteksi-dini-tb/skrining': typeof DeteksiDiniTbSkriningRoute
  '/education/flipbook': typeof EducationFlipbookRouteWithChildren
  '/education/video': typeof EducationVideoRouteWithChildren
  '/pemeriksaan-mandiri/hasil': typeof PemeriksaanMandiriHasilRoute
  '/pemeriksaan-resiko/hasil': typeof PemeriksaanResikoHasilRoute
  '/deteksi-dini-tb/': typeof DeteksiDiniTbIndexRoute
  '/education/': typeof EducationIndexRoute
  '/informasi-kehamilan/': typeof InformasiKehamilanIndexRoute
  '/pemeriksaan-mandiri/': typeof PemeriksaanMandiriIndexRoute
  '/pemeriksaan-resiko/': typeof PemeriksaanResikoIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/education/flipbook/$id': typeof EducationFlipbookIdRoute
  '/education/video/$id': typeof EducationVideoIdRoute
  '/informasi-kehamilan/masalah/$masalahId': typeof InformasiKehamilanMasalahMasalahIdRoute
  '/informasi-kehamilan/pengelolaan/$pengelolaanId': typeof InformasiKehamilanPengelolaanPengelolaanIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/education/flipbook/': typeof EducationFlipbookIndexRoute
  '/education/video/': typeof EducationVideoIndexRoute
  '/informasi-kehamilan/larangan/': typeof InformasiKehamilanLaranganIndexRoute
  '/informasi-kehamilan/masalah/': typeof InformasiKehamilanMasalahIndexRoute
  '/informasi-kehamilan/pengelolaan/': typeof InformasiKehamilanPengelolaanIndexRoute
  '/informasi-kehamilan/tanda-bahaya/': typeof InformasiKehamilanTandaBahayaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cek-risiko'
    | '/education'
    | '/ibu-hamil-tanpa-tb'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/posts'
    | '/deteksi-dini-tb/hasil'
    | '/deteksi-dini-tb/skrining'
    | '/education/flipbook'
    | '/education/video'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/deteksi-dini-tb/'
    | '/education/'
    | '/informasi-kehamilan/'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/posts/$postId'
    | '/education/flipbook/$id'
    | '/education/video/$id'
    | '/informasi-kehamilan/masalah/$masalahId'
    | '/informasi-kehamilan/pengelolaan/$pengelolaanId'
    | '/posts/'
    | '/education/flipbook/'
    | '/education/video/'
    | '/informasi-kehamilan/larangan/'
    | '/informasi-kehamilan/masalah/'
    | '/informasi-kehamilan/pengelolaan/'
    | '/informasi-kehamilan/tanda-bahaya/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cek-risiko'
    | '/ibu-hamil-tanpa-tb'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/deteksi-dini-tb/hasil'
    | '/deteksi-dini-tb/skrining'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/deteksi-dini-tb'
    | '/education'
    | '/informasi-kehamilan'
    | '/pemeriksaan-mandiri'
    | '/pemeriksaan-resiko'
    | '/posts/$postId'
    | '/education/flipbook/$id'
    | '/education/video/$id'
    | '/informasi-kehamilan/masalah/$masalahId'
    | '/informasi-kehamilan/pengelolaan/$pengelolaanId'
    | '/posts'
    | '/education/flipbook'
    | '/education/video'
    | '/informasi-kehamilan/larangan'
    | '/informasi-kehamilan/masalah'
    | '/informasi-kehamilan/pengelolaan'
    | '/informasi-kehamilan/tanda-bahaya'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/cek-risiko'
    | '/education'
    | '/ibu-hamil-tanpa-tb'
    | '/login'
    | '/logout'
    | '/quiz'
    | '/signup'
    | '/toss'
    | '/_authed/posts'
    | '/deteksi-dini-tb/hasil'
    | '/deteksi-dini-tb/skrining'
    | '/education/flipbook'
    | '/education/video'
    | '/pemeriksaan-mandiri/hasil'
    | '/pemeriksaan-resiko/hasil'
    | '/deteksi-dini-tb/'
    | '/education/'
    | '/informasi-kehamilan/'
    | '/pemeriksaan-mandiri/'
    | '/pemeriksaan-resiko/'
    | '/_authed/posts/$postId'
    | '/education/flipbook/$id'
    | '/education/video/$id'
    | '/informasi-kehamilan/masalah/$masalahId'
    | '/informasi-kehamilan/pengelolaan/$pengelolaanId'
    | '/_authed/posts/'
    | '/education/flipbook/'
    | '/education/video/'
    | '/informasi-kehamilan/larangan/'
    | '/informasi-kehamilan/masalah/'
    | '/informasi-kehamilan/pengelolaan/'
    | '/informasi-kehamilan/tanda-bahaya/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CekRisikoRoute: typeof CekRisikoRoute
  EducationRoute: typeof EducationRouteWithChildren
  IbuHamilTanpaTbRoute: typeof IbuHamilTanpaTbRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  QuizRoute: typeof QuizRoute
  SignupRoute: typeof SignupRoute
  TossRoute: typeof TossRoute
  DeteksiDiniTbHasilRoute: typeof DeteksiDiniTbHasilRoute
  DeteksiDiniTbSkriningRoute: typeof DeteksiDiniTbSkriningRoute
  PemeriksaanMandiriHasilRoute: typeof PemeriksaanMandiriHasilRoute
  PemeriksaanResikoHasilRoute: typeof PemeriksaanResikoHasilRoute
  DeteksiDiniTbIndexRoute: typeof DeteksiDiniTbIndexRoute
  InformasiKehamilanIndexRoute: typeof InformasiKehamilanIndexRoute
  PemeriksaanMandiriIndexRoute: typeof PemeriksaanMandiriIndexRoute
  PemeriksaanResikoIndexRoute: typeof PemeriksaanResikoIndexRoute
  InformasiKehamilanMasalahMasalahIdRoute: typeof InformasiKehamilanMasalahMasalahIdRoute
  InformasiKehamilanPengelolaanPengelolaanIdRoute: typeof InformasiKehamilanPengelolaanPengelolaanIdRoute
  InformasiKehamilanLaranganIndexRoute: typeof InformasiKehamilanLaranganIndexRoute
  InformasiKehamilanMasalahIndexRoute: typeof InformasiKehamilanMasalahIndexRoute
  InformasiKehamilanPengelolaanIndexRoute: typeof InformasiKehamilanPengelolaanIndexRoute
  InformasiKehamilanTandaBahayaIndexRoute: typeof InformasiKehamilanTandaBahayaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toss': {
      id: '/toss'
      path: '/toss'
      fullPath: '/toss'
      preLoaderRoute: typeof TossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ibu-hamil-tanpa-tb': {
      id: '/ibu-hamil-tanpa-tb'
      path: '/ibu-hamil-tanpa-tb'
      fullPath: '/ibu-hamil-tanpa-tb'
      preLoaderRoute: typeof IbuHamilTanpaTbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-risiko': {
      id: '/cek-risiko'
      path: '/cek-risiko'
      fullPath: '/cek-risiko'
      preLoaderRoute: typeof CekRisikoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-resiko/': {
      id: '/pemeriksaan-resiko/'
      path: '/pemeriksaan-resiko'
      fullPath: '/pemeriksaan-resiko/'
      preLoaderRoute: typeof PemeriksaanResikoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/': {
      id: '/pemeriksaan-mandiri/'
      path: '/pemeriksaan-mandiri'
      fullPath: '/pemeriksaan-mandiri/'
      preLoaderRoute: typeof PemeriksaanMandiriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/': {
      id: '/informasi-kehamilan/'
      path: '/informasi-kehamilan'
      fullPath: '/informasi-kehamilan/'
      preLoaderRoute: typeof InformasiKehamilanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/': {
      id: '/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof EducationRoute
    }
    '/deteksi-dini-tb/': {
      id: '/deteksi-dini-tb/'
      path: '/deteksi-dini-tb'
      fullPath: '/deteksi-dini-tb/'
      preLoaderRoute: typeof DeteksiDiniTbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-resiko/hasil': {
      id: '/pemeriksaan-resiko/hasil'
      path: '/pemeriksaan-resiko/hasil'
      fullPath: '/pemeriksaan-resiko/hasil'
      preLoaderRoute: typeof PemeriksaanResikoHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan-mandiri/hasil': {
      id: '/pemeriksaan-mandiri/hasil'
      path: '/pemeriksaan-mandiri/hasil'
      fullPath: '/pemeriksaan-mandiri/hasil'
      preLoaderRoute: typeof PemeriksaanMandiriHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/video': {
      id: '/education/video'
      path: '/video'
      fullPath: '/education/video'
      preLoaderRoute: typeof EducationVideoRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/flipbook': {
      id: '/education/flipbook'
      path: '/flipbook'
      fullPath: '/education/flipbook'
      preLoaderRoute: typeof EducationFlipbookRouteImport
      parentRoute: typeof EducationRoute
    }
    '/deteksi-dini-tb/skrining': {
      id: '/deteksi-dini-tb/skrining'
      path: '/deteksi-dini-tb/skrining'
      fullPath: '/deteksi-dini-tb/skrining'
      preLoaderRoute: typeof DeteksiDiniTbSkriningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deteksi-dini-tb/hasil': {
      id: '/deteksi-dini-tb/hasil'
      path: '/deteksi-dini-tb/hasil'
      fullPath: '/deteksi-dini-tb/hasil'
      preLoaderRoute: typeof DeteksiDiniTbHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/informasi-kehamilan/tanda-bahaya/': {
      id: '/informasi-kehamilan/tanda-bahaya/'
      path: '/informasi-kehamilan/tanda-bahaya'
      fullPath: '/informasi-kehamilan/tanda-bahaya/'
      preLoaderRoute: typeof InformasiKehamilanTandaBahayaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/pengelolaan/': {
      id: '/informasi-kehamilan/pengelolaan/'
      path: '/informasi-kehamilan/pengelolaan'
      fullPath: '/informasi-kehamilan/pengelolaan/'
      preLoaderRoute: typeof InformasiKehamilanPengelolaanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/masalah/': {
      id: '/informasi-kehamilan/masalah/'
      path: '/informasi-kehamilan/masalah'
      fullPath: '/informasi-kehamilan/masalah/'
      preLoaderRoute: typeof InformasiKehamilanMasalahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/larangan/': {
      id: '/informasi-kehamilan/larangan/'
      path: '/informasi-kehamilan/larangan'
      fullPath: '/informasi-kehamilan/larangan/'
      preLoaderRoute: typeof InformasiKehamilanLaranganIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/video/': {
      id: '/education/video/'
      path: '/'
      fullPath: '/education/video/'
      preLoaderRoute: typeof EducationVideoIndexRouteImport
      parentRoute: typeof EducationVideoRoute
    }
    '/education/flipbook/': {
      id: '/education/flipbook/'
      path: '/'
      fullPath: '/education/flipbook/'
      preLoaderRoute: typeof EducationFlipbookIndexRouteImport
      parentRoute: typeof EducationFlipbookRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/informasi-kehamilan/pengelolaan/$pengelolaanId': {
      id: '/informasi-kehamilan/pengelolaan/$pengelolaanId'
      path: '/informasi-kehamilan/pengelolaan/$pengelolaanId'
      fullPath: '/informasi-kehamilan/pengelolaan/$pengelolaanId'
      preLoaderRoute: typeof InformasiKehamilanPengelolaanPengelolaanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-kehamilan/masalah/$masalahId': {
      id: '/informasi-kehamilan/masalah/$masalahId'
      path: '/informasi-kehamilan/masalah/$masalahId'
      fullPath: '/informasi-kehamilan/masalah/$masalahId'
      preLoaderRoute: typeof InformasiKehamilanMasalahMasalahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/video/$id': {
      id: '/education/video/$id'
      path: '/$id'
      fullPath: '/education/video/$id'
      preLoaderRoute: typeof EducationVideoIdRouteImport
      parentRoute: typeof EducationVideoRoute
    }
    '/education/flipbook/$id': {
      id: '/education/flipbook/$id'
      path: '/$id'
      fullPath: '/education/flipbook/$id'
      preLoaderRoute: typeof EducationFlipbookIdRouteImport
      parentRoute: typeof EducationFlipbookRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
  }
}

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface EducationFlipbookRouteChildren {
  EducationFlipbookIdRoute: typeof EducationFlipbookIdRoute
  EducationFlipbookIndexRoute: typeof EducationFlipbookIndexRoute
}

const EducationFlipbookRouteChildren: EducationFlipbookRouteChildren = {
  EducationFlipbookIdRoute: EducationFlipbookIdRoute,
  EducationFlipbookIndexRoute: EducationFlipbookIndexRoute,
}

const EducationFlipbookRouteWithChildren =
  EducationFlipbookRoute._addFileChildren(EducationFlipbookRouteChildren)

interface EducationVideoRouteChildren {
  EducationVideoIdRoute: typeof EducationVideoIdRoute
  EducationVideoIndexRoute: typeof EducationVideoIndexRoute
}

const EducationVideoRouteChildren: EducationVideoRouteChildren = {
  EducationVideoIdRoute: EducationVideoIdRoute,
  EducationVideoIndexRoute: EducationVideoIndexRoute,
}

const EducationVideoRouteWithChildren = EducationVideoRoute._addFileChildren(
  EducationVideoRouteChildren,
)

interface EducationRouteChildren {
  EducationFlipbookRoute: typeof EducationFlipbookRouteWithChildren
  EducationVideoRoute: typeof EducationVideoRouteWithChildren
  EducationIndexRoute: typeof EducationIndexRoute
}

const EducationRouteChildren: EducationRouteChildren = {
  EducationFlipbookRoute: EducationFlipbookRouteWithChildren,
  EducationVideoRoute: EducationVideoRouteWithChildren,
  EducationIndexRoute: EducationIndexRoute,
}

const EducationRouteWithChildren = EducationRoute._addFileChildren(
  EducationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CekRisikoRoute: CekRisikoRoute,
  EducationRoute: EducationRouteWithChildren,
  IbuHamilTanpaTbRoute: IbuHamilTanpaTbRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  QuizRoute: QuizRoute,
  SignupRoute: SignupRoute,
  TossRoute: TossRoute,
  DeteksiDiniTbHasilRoute: DeteksiDiniTbHasilRoute,
  DeteksiDiniTbSkriningRoute: DeteksiDiniTbSkriningRoute,
  PemeriksaanMandiriHasilRoute: PemeriksaanMandiriHasilRoute,
  PemeriksaanResikoHasilRoute: PemeriksaanResikoHasilRoute,
  DeteksiDiniTbIndexRoute: DeteksiDiniTbIndexRoute,
  InformasiKehamilanIndexRoute: InformasiKehamilanIndexRoute,
  PemeriksaanMandiriIndexRoute: PemeriksaanMandiriIndexRoute,
  PemeriksaanResikoIndexRoute: PemeriksaanResikoIndexRoute,
  InformasiKehamilanMasalahMasalahIdRoute:
    InformasiKehamilanMasalahMasalahIdRoute,
  InformasiKehamilanPengelolaanPengelolaanIdRoute:
    InformasiKehamilanPengelolaanPengelolaanIdRoute,
  InformasiKehamilanLaranganIndexRoute: InformasiKehamilanLaranganIndexRoute,
  InformasiKehamilanMasalahIndexRoute: InformasiKehamilanMasalahIndexRoute,
  InformasiKehamilanPengelolaanIndexRoute:
    InformasiKehamilanPengelolaanIndexRoute,
  InformasiKehamilanTandaBahayaIndexRoute:
    InformasiKehamilanTandaBahayaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
